version: '3.6'
services:
    postgres:
        container_name: postgres
        restart: always
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: CDIO_2
            ports: '5432:5432'
        volumes:
            - db_postgres:/var/lib/postgresql/data/
    pgadmin: 
        container_name: pgadmin
        restart: always
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org 
            PGADMIN_DEFAULT_PASSWORD: admin
        ports: 
            - '5050:80'
        depends_on: 
            - postgres
    
volumes: 
    db_postgres:
    pgadmin: